### ISSUE TITLE
Please adding simple Chinese (cn) for toggling

### ISSUE THREAD

**Issue by chohyu** [zoroaster00/Search-with-Language-Range-Extension#1]
Hi, Thank you very much for creating such a great extension. and could you please consider to add simple Chinese (cn) for toggling, Thanks in advance.

**Comment by zoroaster00** [comment]
[fixed](https://github.com/zoroaster00/Search-with-Language-Range-Extension/commit/142c7dce5c166475f6ae7332dbbe160c1eaff1e1) added multiple languages to the option list, and it would be available in 0.1.2. Thanks for the feedback.
